dictionaries = [
    "ru",
    "en_us",
]
words = [
    "arctg",
    "cov",
    "hra",
    "hrb",
    "hrc",
    "kcu",
    "kcv",
    "liquidus",
    "ognevny",
    "radic",
    "spss",
    "xoy",
    "АЯП",
    "Авраамические",
    "Австро",
    "Акмаева",
    "Аламбера",
    "Аракчеева",
    "Арамид",
    "Арамидные",
    "Артоболевский",
    "Артоболевского",
    "Артоболевскому",
    "Аскриптивный",
    "Ассура",
    "Ассуру",
    "Атабеков",
    "Аттилы",
    "Байеса",
    "Барицентр",
    "Батый",
    "Батыя",
    "Безу",
    "Бейнитное",
    "Белоозёрск",
    "Бердяев",
    "Бильберт",
    "Бирон",
    "Бисмалеимидные",
    "Бобринский",
    "Бойлю",
    "Бондаренков",
    "Бочвара",
    "Бринеллю",
    "Бюффон",
    "ВА",
    "ВВВ",
    "ВВП",
    "ВД",
    "ВПВ",
    "ВПП",
    "Ваальсова",
    "Вайлдберриз",
    "Варёнок",
    "Вейбулла",
    "Венана",
    "Верещагина",
    "Верещагину",
    "Виета",
    "Виккерсу",
    "Вилиса",
    "Виллиса",
    "Виноградова",
    "Виноградовой",
    "Вискеры",
    "Витворта",
    "Влагопоглощение",
    "Внецентренное",
    "Внецентренным",
    "Внутриролевой",
    "Вронского",
    "Вышеслава",
    "ГМК",
    "ГП",
    "ГСИ",
    "ГУ",
    "ГЦК",
    "Гапона",
    "Герона",
    "Гливенко",
    "Глинской",
    "Годунов",
    "Годунова",
    "Головин",
    "Гомогеннизационный",
    "Горнера",
    "Гунов",
    "Гуны",
    "Гучков",
    "ДСВ",
    "ДУ",
    "ДФР",
    "Даламберовы",
    "Далю",
    "Дарданеллы",
    "Двухопорная",
    "Двухстержневая",
    "Джевонс",
    "Джемса",
    "Дира",
    "Дорекристаллизационный",
    "Дюркгейм",
    "Журавского",
    "ЗБЧ",
    "ЗР",
    "ЗС",
    "ЗСВ",
    "Зародов",
    "Зародова",
    "Зигмунду",
    "Зиновьева",
    "ИСО",
    "ИТ",
    "ИФР",
    "Изворск",
    "Ингерманландия",
    "Иоановна",
    "КВЖД",
    "КОВ",
    "КП",
    "КСВ",
    "КЧ",
    "Казимиров",
    "Калита",
    "Калка",
    "Кантелли",
    "Капуткина",
    "Капуткиной",
    "Квалитет",
    "Кельвинах",
    "Клеро",
    "Ковариация",
    "Кондратьева",
    "Кондратьевой",
    "Конт",
    "Конту",
    "Кориолиса",
    "Кориолисова",
    "Коррелированными",
    "Кривошипно",
    "Курнакова",
    "Кёнига",
    "ЛГБТ",
    "ЛДУ",
    "ЛНДУ",
    "ЛНЗ",
    "ЛНСУ",
    "ЛОДУ",
    "ЛОСУ",
    "ЛР",
    "ЛТ",
    "Леви",
    "Лефорт",
    "Лефорта",
    "Лех",
    "Леха",
    "Лжедмитрий",
    "Лжедмитрия",
    "Липкина",
    "Лиувилля",
    "Логнормальное",
    "Локтева",
    "Ломцова",
    "Лопухина",
    "Лопухиной",
    "Лотарингия",
    "Лунёва",
    "Лысакова",
    "Лысаковой",
    "Людерса",
    "Люссаку",
    "Ляояном",
    "Лях",
    "Мазепы",
    "Майера",
    "Майерсу",
    "Максоковская",
    "Малюта",
    "Манипулятивное",
    "Мариотта",
    "Мариотту",
    "Маркова",
    "Мартиросов",
    "Мартиросова",
    "Мартов",
    "Маслоу",
    "Матиндукция",
    "Матыцин",
    "Межролевой",
    "Менелая",
    "Меншиков",
    "Меснянкин",
    "Микро",
    "Милорадович",
    "Милюков",
    "Минин",
    "Мирзоян",
    "Мнишек",
    "Моббинг",
    "Моно",
    "Мономах",
    "Мономаха",
    "Морган",
    "Муавр",
    "Муавра",
    "Муавру",
    "Мукденом",
    "НДСВ",
    "НЗС",
    "НЗСВ",
    "НКСВ",
    "НСВ",
    "НСС",
    "Нанокомпозиты",
    "Нарышкина",
    "Натяг",
    "Невключенное",
    "Неймана",
    "Некомпентентность",
    "Неравноточные",
    "Нефизические",
    "Неформализованное",
    "Неформализованные",
    "ОАК",
    "ОО",
    "ОЦК",
    "Обеля",
    "Огюст",
    "Одина",
    "Однопараметрическое",
    "Орехова",
    "Ортоцентр",
    "Оршанке",
    "Оскольда",
    "Отрепьевым",
    "Оценивание",
    "ПВВ",
    "ПВП",
    "ПЗР",
    "ПМ",
    "ПМВ",
    "ППВ",
    "ППС",
    "ПЦ",
    "Пегачкова",
    "Переплата",
    "Перерезывающая",
    "Переславле",
    "Перуну",
    "Пирсон",
    "Платонову",
    "Плоскопространственная",
    "Плюшкин",
    "Подзаконодательные",
    "Подшипно",
    "Пожарский",
    "Пожарскому",
    "Попустительский",
    "Порохни",
    "Портсмутская",
    "Портсмутский",
    "Поселье",
    "Праксеологическая",
    "Прецезионность",
    "Пугачёв",
    "Пуришкевич",
    "РР",
    "РСДРП",
    "Равноточные",
    "Радиопрозрачность",
    "Радищев",
    "Разин",
    "Рекристаллизационный",
    "Родзянко",
    "Роквелла",
    "Роквеллу",
    "Романова",
    "Романовых",
    "Ропшу",
    "Ростовско",
    "Рось",
    "Рудненко",
    "Рыжовой",
    "Рюрик",
    "Рюрика",
    "СКО",
    "СЛАУ",
    "СН",
    "СНО",
    "СП",
    "СПГ",
    "СС",
    "Самоактуализация",
    "Сателлитные",
    "Святополк",
    "Святополка",
    "Святополку",
    "Семёнова",
    "Сен",
    "Сергиева",
    "Сергиеву",
    "Сериальные",
    "Сименс",
    "Синеус",
    "Скавронской",
    "Скривые",
    "Скуратов",
    "Славяно",
    "Сличаемость",
    "Сороса",
    "Социометрический",
    "Спортлото",
    "Среднеквадратическая",
    "Столбово",
    "Столыпина",
    "Студников",
    "Студникова",
    "Стюарта",
    "Суворов",
    "Суворова",
    "Суворову",
    "Судебник",
    "ТВи",
    "ТД",
    "ТММ",
    "ТМО",
    "ТРТ",
    "ТС",
    "Тангенсный",
    "Тимучин",
    "Ткаченко",
    "Третьеиюньская",
    "Трубецкой",
    "Трувор",
    "Трёхстержневая",
    "Тушино",
    "УЗР",
    "УМФ",
    "УЧП",
    "Углепластик",
    "ФЗ",
    "ФСР",
    "Фалеса",
    "Фарри",
    "Фауста",
    "Феллер",
    "Феоктистова",
    "Феоктистовой",
    "Ферменная",
    "Фиббоначи",
    "Франкенштейна",
    "Фрейд",
    "Фрейду",
    "Фромм",
    "ХВГ",
    "ХУ",
    "Хопфа",
    "ЦПТ",
    "ЦСВ",
    "Царицын",
    "Циолковского",
    "Чевы",
    "Чернов",
    "Чернова",
    "Чингисхан",
    "Чудовом",
    "ШХ",
    "Шеин",
    "Шеину",
    "Шехловитый",
    "Шувалов",
    "Эm",
    "Эn",
    "Эq",
    "ЭИ",
    "ЭП",
    "Эвтектоидная",
    "Эдельштейна",
    "Экспектации",
    "Электропроводимость",
    "Этноцентризм",
    "Ярополк",
    "Ясинского",
    "Ясперс",
    "аннигилированы",
    "антикультура",
    "антиордынского",
    "антиреформенную",
    "антифранцузскую",
    "архитип",
    "аскриптивный",
    "аустенитного",
    "аустенитную",
    "барицентр",
    "барицентром",
    "бездиффузионно",
    "бездиффузионного",
    "бездиффузионному",
    "безрелигиозна",
    "безуглеродистая",
    "беспригоночной",
    "беспригоночную",
    "бикристалл",
    "бол",
    "бринелль",
    "булгарами",
    "буллинг",
    "бунтарных",
    "вакууметрическое",
    "вейбулла",
    "взаимноперпендикулярных",
    "взаимодисл",
    "виккерс",
    "виртточка",
    "вневписанный",
    "вневписанных",
    "внецентренном",
    "второйвид",
    "высокоуглеродистых",
    "высокоугловая",
    "гендерные",
    "геом",
    "геомкинем",
    "гомогеннизационный",
    "горячекатанной",
    "госметролслужбой",
    "графитезирующему",
    "графо",
    "двутавршвеллер",
    "двухопорная",
    "двухстержень",
    "депланации",
    "депланирует",
    "дер",
    "детерменированные",
    "детовождение",
    "децили",
    "диагрраст",
    "диагрсжат",
    "диагрусл",
    "диагрчугун",
    "диффузионно",
    "доэвтектические",
    "доэвтектический",
    "доэвтектических",
    "доэвтектоидной",
    "доэвтектоидные",
    "доэвтектоидных",
    "занулиться",
    "зарождкрист",
    "заэвтектические",
    "заэвтектический",
    "заэвтектических",
    "заэвтектоидная",
    "заэвтектоидной",
    "заэвтектоидные",
    "заэвтектоидных",
    "зодчии",
    "изгибкруч",
    "измлощадь",
    "индивидное",
    "инерций",
    "калорические",
    "картусилий",
    "каснапр",
    "квадратическая",
    "квадратическое",
    "квадроберство",
    "квази",
    "квалитет",
    "квалитета",
    "квалитетах",
    "квалитетов",
    "квалитеты",
    "кинетостатики",
    "княжить",
    "ковариация",
    "компетенций",
    "конода",
    "коноды",
    "коррелированность",
    "коррелированные",
    "кососимметричный",
    "криваяраст",
    "кривохл",
    "кривохлад",
    "кручдиагрнапр",
    "кручкруг",
    "кручпрям",
    "кручразр",
    "кручсечение",
    "крыльевые",
    "ксенофобия",
    "кубиккласс",
    "кубикнапр",
    "лаба",
    "легированность",
    "летия",
    "лонгитюдные",
    "макросоциология",
    "макрочастиц",
    "малопластичные",
    "манипулятивной",
    "медиа",
    "межконтактный",
    "межузельный",
    "метастабильнее",
    "многоконфессиональная",
    "многомерна",
    "многоступ",
    "многофакторна",
    "модернизационном",
    "моментная",
    "моментных",
    "монометрическое",
    "монополи",
    "мотивационная",
    "напрсост",
    "натяг",
    "натягом",
    "начально",
    "недвойниковый",
    "неизменяема",
    "некоррелированность",
    "некоррелированные",
    "неметрические",
    "неогрраст",
    "неодноимённых",
    "непересекающимся",
    "неперпендикулярной",
    "непотенциальных",
    "непротекания",
    "несовместны",
    "несопрягаемые",
    "несопрягаемых",
    "нетонкостенного",
    "неудерживающей",
    "низкоуглеродистых",
    "нонвариантная",
    "обратносимметричный",
    "обрсжат",
    "операционализация",
    "органична",
    "ордынцев",
    "освобождаемости",
    "островершинностью",
    "открпроф",
    "оценивание",
    "перепохоронили",
    "перерезывающая",
    "перерезывающей",
    "перерезывающих",
    "плетений",
    "повдефекты",
    "податливостями",
    "подпапки",
    "покрещён",
    "ползунный",
    "полиимидные",
    "политропы",
    "полупроизведений",
    "постсила",
    "потокосцепление",
    "приведутся",
    "приработка",
    "пристеночный",
    "равновероятность",
    "равновозможность",
    "равновозможными",
    "равновозможных",
    "равноосных",
    "равноотстающих",
    "равнопрочны",
    "радикализации",
    "разграблял",
    "разгромления",
    "разнозернистость",
    "разупрочняются",
    "растдеформ",
    "растсечения",
    "реккурентной",
    "рекр",
    "рекуррентно",
    "репозиторий",
    "репозитория",
    "реципиентная",
    "решек",
    "сателлитные",
    "свинецсурьма",
    "свобэнергия",
    "семёновские",
    "сериальные",
    "сжатэксп",
    "сигм",
    "симметр",
    "системна",
    "скошенности",
    "сложнолегированных",
    "сложноорганизованный",
    "смотрилке",
    "собств",
    "содержаниях",
    "сонаправлен",
    "сорре",
    "спецоперация",
    "сплошности",
    "среднеквадратическое",
    "среднеуглеродистых",
    "стандобр",
    "стереотипизация",
    "субзёрен",
    "субзёрна",
    "суперлень",
    "сфероидизирующий",
    "твраствор",
    "тетрагональности",
    "толстостенности",
    "тонкопластичная",
    "тонкостен",
    "тонкостенности",
    "точдефекты",
    "трехстержневой",
    "трёхголовым",
    "ударизгиб",
    "уложительную",
    "улыбашка",
    "усреднённные",
    "усталостповр",
    "устфокус",
    "ферменной",
    "ферменные",
    "феррито",
    "физичность",
    "формульно",
    "функположения",
    "хлебопашцах",
    "холодноломкости",
    "цементитной",
    "центртяж",
    "церемониально",
    "цэшек",
    "четырехзвенный",
    "чытерехзвенник",
    "штрихуются",
    "ым",
    "ых",
    "эвт",
    "эвтектоидные",
    "экспектации",
    "экстр",
    "экстремалей",
    "экстремали",
    "экстремаль",
    "экстремалями",
    "электро",
    "электрошлаковая",
    "эмпатии",
    "эпюратау",
]
ignore_patterns = [
    "^[A-Z]{2,}$",
    "^[А-Я]{2,}$",
]
