dictionaries = ["ru", "en_us"]

# мне немного лень добавлять сюда всё, что не должен помечать codebook...
words = [
    "arctg",
    "cov",
    "liquidus",
    "ognevny",
    "radic",
    "Авраамические",
    "Австро",
    "Акмаева",
    "Аламбера",
    "аннигилированы",
    "антикультура",
    "антиордынского",
    "антиреформенную",
    "антифранцузскую",
    "Аракчеева",
    "Артоболевский",
    "Артоболевского",
    "Артоболевскому",
    "архитип",
    "Ассура",
    "Ассуру",
    "Атабеков",
    "Аттилы",
    "аустенитного",
    "аустенитную",
    "Байеса",
    "Барицентр",
    "барицентр",
    "барицентром",
    "Батый",
    "Батыя",
    "бездиффузионно",
    "бездиффузионного",
    "бездиффузионному",
    "безрелигиозна",
    "Безу",
    "безуглеродистая",
    "Бейнитное",
    "Белоозёрск",
    "Бердяев",
    "бикристалл",
    "Бильберт",
    "Бирон",
    "Бобринский",
    "Бойлю",
    "бол",
    "Бондаренков", # 😡
    "Бочвара",
    "бринелль",
    "Бринеллю",
    "булгарами",
    "буллинг",
    "бунтарных",
    "Бюффон",
    "Ваальсова",
    "вакууметрическое",
    "Варёнок",
    "Вейбулла",
    "Венана",
    "Верещагина",
    "Верещагину",
    "взаимноперпендикулярных",
    "взаимодисл",
    "Виета",
    "виккерс",
    "Виккерсу",
    "Виноградова",
    "Вискеры",
    "Витворта",
    "вневписанный",
    "вневписанных",
    "Внецентренное",
    "внецентренном",
    "Внецентренным",
    "Вронского",
    "второйвид",
    "высокоуглеродистых",
    "высокоугловая",
    "Вышеслава",
    "Гапона",
    "гендерные",
    "Герона",
    "Гливенко",
    "Глинской",
    "Годунов",
    "Годунова",
    "Головин",
    "гомогеннизационный",
    "Гомогеннизационный",
    "Горнера",
    "горячекатанной",
    "графитезирующему",
    "графо",
    "Гунов",
    "Гуны",
    "Гучков",
    "Далю",
    "Дарданеллы",
    "двутавршвеллер",
    "Двухопорная",
    "двухопорная",
    "Двухстержневая",
    "депланации",
    "депланирует",
    "дер",
    "детерменированные",
    "детовождение",
    "децили",
    "Джевонс",
    "диагрраст",
    "диагрсжат",
    "диагрусл",
    "диагрчугун",
    "Дира",
    "диффузионно",
    "Дорекристаллизационный",
    "доэвтектические",
    "доэвтектический",
    "доэвтектических",
    "доэвтектоидной",
    "доэвтектоидные",
    "доэвтектоидных",
    "Дюркгейм",
    "Журавского",
    "Зародов",
    "Зародова",
    "зарождкрист",
    "заэвтектические",
    "заэвтектический",
    "заэвтектических",
    "заэвтектоидная",
    "заэвтектоидной",
    "заэвтектоидные",
    "заэвтектоидных",
    "Зигмунду",
    "Зиновьева",
    "зодчии",
    "Изворск",
    "изгибкруч",
    "Ингерманландия",
    "индивидное",
    "инерций",
    "Иоановна",
    "Казимиров",
    "Калита",
    "Калка",
    "калорические",
    "Кантелли",
    "Капуткина",
    "Капуткиной",
    "картусилий",
    "каснапр",
    "квадратическая",
    "квадратическое",
    "квадроберство",
    "квази",
    "Кельвинах",
    "Клеро",
    "княжить",
    "Ковариация",
    "ковариация",
    "компетенций",
    "Кондратьева",
    "Кондратьевой",
    "конода",
    "коноды",
    "Конт",
    "коррелированность",
    "коррелированные",
    "Коррелированными",
    "кососимметричный",
    "криваяраст",
    "кривохл",
    "кривохлад",
    "Кривошипно",
    "кручдиагрнапр",
    "кручкруг",
    "кручпрям",
    "кручразр",
    "кручсечение",
    "Курнакова",
    "лаба",
    "Леви",
    "легированность",
    "летия",
    "Лефорт",
    "Лефорта",
    "Лех",
    "Леха",
    "Лжедмитрий",
    "Лжедмитрия",
    "Липкина",
    "Логнормальное",
    "Локтева",
    "Ломцова",
    "Лопухина",
    "Лопухиной",
    "Лотарингия",
    "Лунёва",
    "Лысакова",
    "Лысаковой",
    "Людерса",
    "Люссаку",
    "Ляояном",
    "Лях",
    "Мазепы",
    "Майера",
    "Майерсу",
    "макросоциология",
    "Максоковская",
    "малопластичные",
    "Малюта",
    "Манипулятивное",
    "манипулятивной",
    "Мариотту",
    "Маркова",
    "Мартиросов",
    "Мартиросова",
    "Мартов",
    "Маслоу",
    "Матиндукция",
    "Матыцин",
    "медиа",
    "Менелая",
    "Меншиков",
    "Меснянкин",
    "метастабильнее",
    "Микро",
    "Милорадович",
    "Милюков",
    "Минин",
    "Мирзоян",
    "Мнишек",
    "многоконфессиональная",
    "многомерна",
    "многофакторна",
    "Моббинг",
    "модернизационном",
    "моментная",
    "моментных",
    "Моно",
    "Мономах",
    "Мономаха",
    "монометрическое",
    "монополи",
    "Морган",
    "Муавр",
    "Муавра",
    "Муавру",
    "Мукденом",
    "напрсост",
    "Нарышкина",
    "недвойниковый",
    "неизменяема",
    "Неймана",
    "Некомпентентность",
    "некоррелированность",
    "некоррелированные",
    "неогрраст",
    "непересекающимся",
    "неперпендикулярной",
    "несовместны",
    "нетонкостенного",
    "низкоуглеродистых",
    "нонвариантная",
    "Обеля",
    "обратносимметричный",
    "обрсжат",
    "Огюст",
    "Одина",
    "органична",
    "ордынцев",
    "Орехова",
    "Ортоцентр",
    "Оршанке",
    "Оскольда",
    "островершинностью",
    "открпроф",
    "Отрепьевым",
    "Оценивание",
    "оценивание",
    "Пегачкова",
    "Переплата",
    "перепохоронили",
    "перерезывающая",
    "Перерезывающая",
    "перерезывающей",
    "перерезывающих",
    "Переславле",
    "Перуну",
    "Пирсон",
    "Платонову",
    "Плоскопространственная",
    "Плюшкин",
    "повдефекты",
    "Подзаконодательные",
    "подпапки",
    "Подшипно",
    "Пожарский",
    "Пожарскому",
    "покрещён",
    "ползунный",
    "Попустительский",
    "Порохни",
    "Портсмутская",
    "Портсмутский",
    "Поселье",
    "потокосцепление",
    "Праксеологическая",
    "Прецезионность",
    "приведутся",
    "Пугачёв",
    "Пуришкевич",
    "равновероятность",
    "равновозможность",
    "равновозможными",
    "равновозможных",
    "равноосных",
    "равноотстающих",
    "радикализации",
    "Радищев",
    "разграблял",
    "разгромления",
    "Разин",
    "разнозернистость",
    "разупрочняются",
    "растдеформ",
    "растсечения",
    "реккурентной",
    "рекр",
    "Рекристаллизационный",
    "рекуррентно",
    "репозиторий",
    "репозитория",
    "решек",
    "Родзянко",
    "Роквелла",
    "Роквеллу",
    "Романова",
    "Романовых",
    "Ропшу",
    "Ростовско",
    "Рось",
    "Рудненко",
    "Рюрик",
    "Рюрика",
    "Самоактуализация",
    "свинецсурьма",
    "свобэнергия",
    "Святополк",
    "Святополка",
    "Святополку",
    "Семёнова",
    "семёновские",
    "Сен",
    "Сергиева",
    "Сергиеву",
    "сериальные",
    "Сериальные",
    "сжатэксп",
    "сигм",
    "Сименс",
    "симметр",
    "Синеус",
    "системна",
    "Скавронской",
    "скошенности",
    "Скривые",
    "Скуратов",
    "Славяно",
    "сложнолегированных",
    "сложноорганизованный",
    "смотрилке",
    "содержаниях",
    "Сороса",
    "сорре",
    "спецоперация",
    "сплошности",
    "Спортлото",
    "Среднеквадратическая",
    "среднеквадратическое",
    "среднеуглеродистых",
    "стандобр",
    "стереотипизация",
    "Столбово",
    "Столыпина",
    "Студников",
    "Студникова",
    "Стюарта",
    "субзёрен",
    "субзёрна",
    "Суворов",
    "Суворова",
    "Суворову",
    "Судебник",
    "суперлень",
    "сфероидизирующий",
    "ТВи",
    "тетрагональности",
    "Тимучин",
    "Ткаченко",
    "толстостенности",
    "тонкопластичная",
    "тонкостен",
    "тонкостенности",
    "точдефекты",
    "Третьеиюньская",
    "трехстержневой",
    "Трубецкой",
    "Трувор",
    "трёхголовым",
    "Трёхстержневая",
    "Тушино",
    "ударизгиб",
    "уложительную",
    "улыбашка",
    "усреднённные",
    "усталостповр",
    "устфокус",
    "Фалеса",
    "Фарри",
    "Фауста",
    "Феллер",
    "Феоктистова",
    "Феоктистовой",
    "Ферменная",
    "ферменной",
    "ферменные",
    "феррито",
    "Фиббоначи",
    "Франкенштейна",
    "Фрейд",
    "Фрейду",
    "Фромм",
    "хлебопашцах",
    "холодноломкости",
    "Хопфа",
    "Царицын",
    "цементитной",
    "центртяж",
    "церемониально",
    "Чевы",
    "Чернов",
    "Чернова",
    "четырехзвенный",
    "Чингисхан",
    "Чудовом",
    "Шеин",
    "Шеину",
    "Шехловитый",
    "штрихуются",
    "Шувалов",
    "ым",
    "ых",
    "эвт",
    "Эвтектоидная",
    "эвтектоидные",
    "Эдельштейна",
    "экстр",
    "электро",
    "Электропроводимость",
    "электрошлаковая",
    "эмпатии",
    "эпюратау",
    "Ярополк",
    "Ясперс",
]

ignore_patterns = [
    '^[A-Z]{2,}$',
    '^[\u0400-\u042F]{2,}$',
]
